package com.silverbullet.auth.domain;

import java.util.Date;

public class SysAuthAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.resource_type
     *
     * @mbggenerated
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.path
     *
     * @mbggenerated
     */
    private String path = " ";

    // 权限
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.comments
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.modify_user
     *
     * @mbggenerated
     */
    private Integer modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.is_need_check
     *
     * @mbggenerated
     */
    private String isNeedCheck = "0";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_action.is_need_login
     *
     * @mbggenerated
     */
    private String isNeedLogin = "1";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.id
     *
     * @return the value of sys_auth_action.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.id
     *
     * @param id the value for sys_auth_action.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.name
     *
     * @return the value of sys_auth_action.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.name
     *
     * @param name the value for sys_auth_action.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.url
     *
     * @return the value of sys_auth_action.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.url
     *
     * @param url the value for sys_auth_action.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.resource_type
     *
     * @return the value of sys_auth_action.resource_type
     *
     * @mbggenerated
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.resource_type
     *
     * @param resourceType the value for sys_auth_action.resource_type
     *
     * @mbggenerated
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.parent_id
     *
     * @return the value of sys_auth_action.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.parent_id
     *
     * @param parentId the value for sys_auth_action.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.path
     *
     * @return the value of sys_auth_action.path
     *
     * @mbggenerated
     */
    public String getParentIds() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.path
     *
     * @param path the value for sys_auth_action.parent_ids
     *
     * @mbggenerated
     */
    public void setParentIds(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.comments
     *
     * @return the value of sys_auth_action.comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.comments
     *
     * @param comments the value for sys_auth_action.comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.create_user
     *
     * @return the value of sys_auth_action.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.create_user
     *
     * @param createUser the value for sys_auth_action.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.create_time
     *
     * @return the value of sys_auth_action.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.create_time
     *
     * @param createTime the value for sys_auth_action.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.modify_user
     *
     * @return the value of sys_auth_action.modify_user
     *
     * @mbggenerated
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.modify_user
     *
     * @param modifyUser the value for sys_auth_action.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.modify_time
     *
     * @return the value of sys_auth_action.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.modify_time
     *
     * @param modifyTime the value for sys_auth_action.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.state
     *
     * @return the value of sys_auth_action.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.state
     *
     * @param state the value for sys_auth_action.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.is_need_check
     *
     * @return the value of sys_auth_action.is_need_check
     *
     * @mbggenerated
     */
    public String getIsNeedCheck() {
        return isNeedCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.is_need_check
     *
     * @param isNeedCheck the value for sys_auth_action.is_need_check
     *
     * @mbggenerated
     */
    public void setIsNeedCheck(String isNeedCheck) {
        this.isNeedCheck = isNeedCheck == null ? null : isNeedCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_action.is_need_login
     *
     * @return the value of sys_auth_action.is_need_login
     *
     * @mbggenerated
     */
    public String getIsNeedLogin() {
        return isNeedLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_action.is_need_login
     *
     * @param isNeedLogin the value for sys_auth_action.is_need_login
     *
     * @mbggenerated
     */
    public void setIsNeedLogin(String isNeedLogin) {
        this.isNeedLogin = isNeedLogin == null ? null : isNeedLogin.trim();
    }

    public String getPermission() {
        return permission;
    }

    public void setPermission(String permission) {
        this.permission = permission;
    }
}