package com.silverbullet.auth.domain;

import java.util.Date;

public class SysAuthPost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.organization_id
     *
     * @mbggenerated
     */
    private String organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.create_username
     *
     * @mbggenerated
     */
    private String createUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.modify_username
     *
     * @mbggenerated
     */
    private String modifyUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.is_extends
     *
     * @mbggenerated
     */
    private String isExtends;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.organization_id
     *
     * @return the value of sys_auth_post.organization_id
     *
     * @mbggenerated
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.organization_id
     *
     * @param organizationId the value for sys_auth_post.organization_id
     *
     * @mbggenerated
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId == null ? null : organizationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.id
     *
     * @return the value of sys_auth_post.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.id
     *
     * @param id the value for sys_auth_post.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.name
     *
     * @return the value of sys_auth_post.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.name
     *
     * @param name the value for sys_auth_post.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.create_username
     *
     * @return the value of sys_auth_post.create_username
     *
     * @mbggenerated
     */
    public String getCreateUsername() {
        return createUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.create_username
     *
     * @param createUsername the value for sys_auth_post.create_username
     *
     * @mbggenerated
     */
    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername == null ? null : createUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.create_user
     *
     * @return the value of sys_auth_post.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.create_user
     *
     * @param createUser the value for sys_auth_post.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.create_time
     *
     * @return the value of sys_auth_post.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.create_time
     *
     * @param createTime the value for sys_auth_post.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.modify_username
     *
     * @return the value of sys_auth_post.modify_username
     *
     * @mbggenerated
     */
    public String getModifyUsername() {
        return modifyUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.modify_username
     *
     * @param modifyUsername the value for sys_auth_post.modify_username
     *
     * @mbggenerated
     */
    public void setModifyUsername(String modifyUsername) {
        this.modifyUsername = modifyUsername == null ? null : modifyUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.modify_user
     *
     * @return the value of sys_auth_post.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.modify_user
     *
     * @param modifyUser the value for sys_auth_post.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.modify_time
     *
     * @return the value of sys_auth_post.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.modify_time
     *
     * @param modifyTime the value for sys_auth_post.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.state
     *
     * @return the value of sys_auth_post.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.state
     *
     * @param state the value for sys_auth_post.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.is_extends
     *
     * @return the value of sys_auth_post.is_extends
     *
     * @mbggenerated
     */
    public String getIsExtends() {
        return isExtends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.is_extends
     *
     * @param isExtends the value for sys_auth_post.is_extends
     *
     * @mbggenerated
     */
    public void setIsExtends(String isExtends) {
        this.isExtends = isExtends == null ? null : isExtends.trim();
    }
}