package com.silverbullet.auth.domain;

public class SysAuthPostAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_postaction.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_postaction.action_id
     *
     * @mbggenerated
     */
    private String actionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_postaction.post_id
     *
     * @mbggenerated
     */
    private String postId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_postaction.id
     *
     * @return the value of sys_auth_postaction.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_postaction.id
     *
     * @param id the value for sys_auth_postaction.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_postaction.action_id
     *
     * @return the value of sys_auth_postaction.action_id
     *
     * @mbggenerated
     */
    public String getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_postaction.action_id
     *
     * @param actionId the value for sys_auth_postaction.action_id
     *
     * @mbggenerated
     */
    public void setActionId(String actionId) {
        this.actionId = actionId == null ? null : actionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_postaction.post_id
     *
     * @return the value of sys_auth_postaction.post_id
     *
     * @mbggenerated
     */
    public String getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_postaction.post_id
     *
     * @param postId the value for sys_auth_postaction.post_id
     *
     * @mbggenerated
     */
    public void setPostId(String postId) {
        this.postId = postId == null ? null : postId.trim();
    }
}