package com.silverbullet.auth.domain;

public class SysAuthUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.COMMENTS
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.CTIME
     *
     * @mbggenerated
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.UTIME
     *
     * @mbggenerated
     */
    private String utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.CUSER
     *
     * @mbggenerated
     */
    private String cuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.MUSER
     *
     * @mbggenerated
     */
    private String muser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.LOGINNAME
     *
     * @mbggenerated
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.LOGINTIME
     *
     * @mbggenerated
     */
    private String logintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.IMGID
     *
     * @mbggenerated
     */
    private String imgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.CLASSIFY
     *
     * @mbggenerated
     */
    private Integer classify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.etime
     *
     * @mbggenerated
     */
    private String etime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_user.euser
     *
     * @mbggenerated
     */
    private String euser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.ID
     *
     * @return the value of sys_auth_user.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.ID
     *
     * @param id the value for sys_auth_user.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.NAME
     *
     * @return the value of sys_auth_user.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.NAME
     *
     * @param name the value for sys_auth_user.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.PASSWORD
     *
     * @return the value of sys_auth_user.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.PASSWORD
     *
     * @param password the value for sys_auth_user.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.COMMENTS
     *
     * @return the value of sys_auth_user.COMMENTS
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.COMMENTS
     *
     * @param comments the value for sys_auth_user.COMMENTS
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.TYPE
     *
     * @return the value of sys_auth_user.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.TYPE
     *
     * @param type the value for sys_auth_user.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.CTIME
     *
     * @return the value of sys_auth_user.CTIME
     *
     * @mbggenerated
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.CTIME
     *
     * @param ctime the value for sys_auth_user.CTIME
     *
     * @mbggenerated
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.UTIME
     *
     * @return the value of sys_auth_user.UTIME
     *
     * @mbggenerated
     */
    public String getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.UTIME
     *
     * @param utime the value for sys_auth_user.UTIME
     *
     * @mbggenerated
     */
    public void setUtime(String utime) {
        this.utime = utime == null ? null : utime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.CUSER
     *
     * @return the value of sys_auth_user.CUSER
     *
     * @mbggenerated
     */
    public String getCuser() {
        return cuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.CUSER
     *
     * @param cuser the value for sys_auth_user.CUSER
     *
     * @mbggenerated
     */
    public void setCuser(String cuser) {
        this.cuser = cuser == null ? null : cuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.MUSER
     *
     * @return the value of sys_auth_user.MUSER
     *
     * @mbggenerated
     */
    public String getMuser() {
        return muser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.MUSER
     *
     * @param muser the value for sys_auth_user.MUSER
     *
     * @mbggenerated
     */
    public void setMuser(String muser) {
        this.muser = muser == null ? null : muser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.STATE
     *
     * @return the value of sys_auth_user.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.STATE
     *
     * @param state the value for sys_auth_user.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.LOGINNAME
     *
     * @return the value of sys_auth_user.LOGINNAME
     *
     * @mbggenerated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.LOGINNAME
     *
     * @param loginname the value for sys_auth_user.LOGINNAME
     *
     * @mbggenerated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.LOGINTIME
     *
     * @return the value of sys_auth_user.LOGINTIME
     *
     * @mbggenerated
     */
    public String getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.LOGINTIME
     *
     * @param logintime the value for sys_auth_user.LOGINTIME
     *
     * @mbggenerated
     */
    public void setLogintime(String logintime) {
        this.logintime = logintime == null ? null : logintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.IMGID
     *
     * @return the value of sys_auth_user.IMGID
     *
     * @mbggenerated
     */
    public String getImgid() {
        return imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.IMGID
     *
     * @param imgid the value for sys_auth_user.IMGID
     *
     * @mbggenerated
     */
    public void setImgid(String imgid) {
        this.imgid = imgid == null ? null : imgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.CLASSIFY
     *
     * @return the value of sys_auth_user.CLASSIFY
     *
     * @mbggenerated
     */
    public Integer getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.CLASSIFY
     *
     * @param classify the value for sys_auth_user.CLASSIFY
     *
     * @mbggenerated
     */
    public void setClassify(Integer classify) {
        this.classify = classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.etime
     *
     * @return the value of sys_auth_user.etime
     *
     * @mbggenerated
     */
    public String getEtime() {
        return etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.etime
     *
     * @param etime the value for sys_auth_user.etime
     *
     * @mbggenerated
     */
    public void setEtime(String etime) {
        this.etime = etime == null ? null : etime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_user.euser
     *
     * @return the value of sys_auth_user.euser
     *
     * @mbggenerated
     */
    public String getEuser() {
        return euser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_user.euser
     *
     * @param euser the value for sys_auth_user.euser
     *
     * @mbggenerated
     */
    public void setEuser(String euser) {
        this.euser = euser == null ? null : euser.trim();
    }
}