package com.silverbullet.auth.domain;

public class SysAuthPost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.CTIME
     *
     * @mbggenerated
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.ETIME
     *
     * @mbggenerated
     */
    private String etime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.CUSERNAME
     *
     * @mbggenerated
     */
    private String cusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.CUSER
     *
     * @mbggenerated
     */
    private String cuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.EUSERNAME
     *
     * @mbggenerated
     */
    private String eusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.EUSER
     *
     * @mbggenerated
     */
    private String euser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.PSTATE
     *
     * @mbggenerated
     */
    private String pstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.ORGANIZATIONID
     *
     * @mbggenerated
     */
    private String organizationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth_post.EXTENDIS
     *
     * @mbggenerated
     */
    private String extendis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.ID
     *
     * @return the value of sys_auth_post.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.ID
     *
     * @param id the value for sys_auth_post.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.CTIME
     *
     * @return the value of sys_auth_post.CTIME
     *
     * @mbggenerated
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.CTIME
     *
     * @param ctime the value for sys_auth_post.CTIME
     *
     * @mbggenerated
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.ETIME
     *
     * @return the value of sys_auth_post.ETIME
     *
     * @mbggenerated
     */
    public String getEtime() {
        return etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.ETIME
     *
     * @param etime the value for sys_auth_post.ETIME
     *
     * @mbggenerated
     */
    public void setEtime(String etime) {
        this.etime = etime == null ? null : etime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.CUSERNAME
     *
     * @return the value of sys_auth_post.CUSERNAME
     *
     * @mbggenerated
     */
    public String getCusername() {
        return cusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.CUSERNAME
     *
     * @param cusername the value for sys_auth_post.CUSERNAME
     *
     * @mbggenerated
     */
    public void setCusername(String cusername) {
        this.cusername = cusername == null ? null : cusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.CUSER
     *
     * @return the value of sys_auth_post.CUSER
     *
     * @mbggenerated
     */
    public String getCuser() {
        return cuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.CUSER
     *
     * @param cuser the value for sys_auth_post.CUSER
     *
     * @mbggenerated
     */
    public void setCuser(String cuser) {
        this.cuser = cuser == null ? null : cuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.EUSERNAME
     *
     * @return the value of sys_auth_post.EUSERNAME
     *
     * @mbggenerated
     */
    public String getEusername() {
        return eusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.EUSERNAME
     *
     * @param eusername the value for sys_auth_post.EUSERNAME
     *
     * @mbggenerated
     */
    public void setEusername(String eusername) {
        this.eusername = eusername == null ? null : eusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.EUSER
     *
     * @return the value of sys_auth_post.EUSER
     *
     * @mbggenerated
     */
    public String getEuser() {
        return euser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.EUSER
     *
     * @param euser the value for sys_auth_post.EUSER
     *
     * @mbggenerated
     */
    public void setEuser(String euser) {
        this.euser = euser == null ? null : euser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.PSTATE
     *
     * @return the value of sys_auth_post.PSTATE
     *
     * @mbggenerated
     */
    public String getPstate() {
        return pstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.PSTATE
     *
     * @param pstate the value for sys_auth_post.PSTATE
     *
     * @mbggenerated
     */
    public void setPstate(String pstate) {
        this.pstate = pstate == null ? null : pstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.ORGANIZATIONID
     *
     * @return the value of sys_auth_post.ORGANIZATIONID
     *
     * @mbggenerated
     */
    public String getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.ORGANIZATIONID
     *
     * @param organizationid the value for sys_auth_post.ORGANIZATIONID
     *
     * @mbggenerated
     */
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid == null ? null : organizationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.NAME
     *
     * @return the value of sys_auth_post.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.NAME
     *
     * @param name the value for sys_auth_post.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_auth_post.EXTENDIS
     *
     * @return the value of sys_auth_post.EXTENDIS
     *
     * @mbggenerated
     */
    public String getExtendis() {
        return extendis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_auth_post.EXTENDIS
     *
     * @param extendis the value for sys_auth_post.EXTENDIS
     *
     * @mbggenerated
     */
    public void setExtendis(String extendis) {
        this.extendis = extendis == null ? null : extendis.trim();
    }
}