package com.silverbullet.auth.dao;

import com.silverbullet.auth.domain.SysAuthUserPost;

public interface SysAuthUserPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_userpost
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_userpost
     *
     * @mbggenerated
     */
    int insert(SysAuthUserPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_userpost
     *
     * @mbggenerated
     */
    int insertSelective(SysAuthUserPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_userpost
     *
     * @mbggenerated
     */
    SysAuthUserPost selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_userpost
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAuthUserPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_userpost
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAuthUserPost record);
}