package com.silverbullet.auth.dao;

import com.silverbullet.auth.domain.SysAuthPost;

public interface SysAuthPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_post
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_post
     *
     * @mbggenerated
     */
    int insert(SysAuthPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_post
     *
     * @mbggenerated
     */
    int insertSelective(SysAuthPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_post
     *
     * @mbggenerated
     */
    SysAuthPost selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAuthPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAuthPost record);
}