package com.silverbullet.auth.dao;

import com.silverbullet.auth.domain.SysAuthUser;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

public interface SysAuthUserMapper {

    /**
     * 计算总数量
     * @return
     */
    int countNum();

    /**
     * 按页获取对象内容
     * @return
     */
    List<Map<String, Object>> list();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_user
     *
     * @mbggenerated
     */
    int insert(SysAuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_user
     *
     * @mbggenerated
     */
    int insertSelective(SysAuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_user
     *
     * @mbggenerated
     */
    SysAuthUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAuthUser record);
}